create table product (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  price numeric(12, 2) not null
);

insert into product (name, price) values ('Keyboard', 150.00);
insert into product (name, price) values ('Mouse', 80.00);
insert into product (name, price) values ('Monitor', 1200.00);
grant select on product to FIRESTORE_APP;
commit;
