CREATE TABLE sales_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key VARCHAR(50) CHARACTER SET ASCII NOT NULL UNIQUE,
  order_status VARCHAR(20) CHARACTER SET ASCII DEFAULT 'PENDING' NOT NULL,
  total NUMERIC(18, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ck_sales_order_total CHECK (total >= 0)
);

CREATE TABLE sales_order_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  line_no INTEGER NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(18, 2) NOT NULL,
  CONSTRAINT uq_sales_order_item_line UNIQUE (order_id, line_no),
  CONSTRAINT ck_sales_order_item_quantity CHECK (quantity > 0),
  CONSTRAINT ck_sales_order_item_price CHECK (unit_price >= 0),
  CONSTRAINT fk_sales_order_item_order FOREIGN KEY (order_id)
    REFERENCES sales_order (id) ON DELETE CASCADE,
  CONSTRAINT fk_sales_order_item_product FOREIGN KEY (product_id)
    REFERENCES product (id)
);

CREATE TABLE inventory (
  product_id BIGINT PRIMARY KEY,
  quantity INTEGER NOT NULL,
  CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id)
    REFERENCES product (id)
);

CREATE TABLE outbox_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_type VARCHAR(40) CHARACTER SET ASCII NOT NULL,
  aggregate_id BIGINT NOT NULL,
  event_type VARCHAR(80) CHARACTER SET ASCII NOT NULL,
  payload BLOB SUB_TYPE TEXT CHARACTER SET UTF8 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX ix_sales_order_item_order ON sales_order_item (order_id);
CREATE INDEX ix_outbox_event_aggregate ON outbox_event (aggregate_type, aggregate_id);
